name: update website using ssh
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: setup ssh
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/server
          chmod 600 ~/.ssh/server
          echo "Host server
                    HostName khurozov.uz
                    User ${{ secrets.SSH_USER }}
                    Port ${{ secrets.SSH_PORT }}
                    IdentityFile ~/.ssh/server" > ~/.ssh/config
          ssh-keyscan -H -p ${{ secrets.SSH_PORT }} khurozov.uz >> ~/.ssh/known_hosts
      - name: run command
        run: ssh server ./update_khurozov
